### ISSUE TITLE
NoCredentialsError: Unable to locate credentials when using profile

### ISSUE THREAD

**Issue by mindhaq** [okta-awscli/okta-awscli#180]
**Describe the bug**

I just upgraded from 0.4.1 to 0.5.0 to use some of the new features.

For one, I want to use the `profile` configuration in the config file instead of providing it as CLI argument, so I added it like this:

    profile = my_iam

When I run

    okta-awscli --debug --verbose

The tool fails with this stacktrace (some info *****'ed by me)

```
DEBUG - Setting AWS role to arn:aws:iam::*****
DEBUG - Setting AWS partition to AwsPartition.AWS
DEBUG - Setting AWS profile to *****
DEBUG - Checking STS token against ARN partition: AwsPartition.AWS
Traceback (most recent call last):
  File "/usr/local/bin/okta-awscli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/oktaawscli/okta_awscli.py", line 115, in main
    if not aws_auth.check_sts_token(profile) or force:
  File "/usr/local/lib/python3.9/site-packages/oktaawscli/aws_auth.py", line 130, in check_sts_token
    sts.get_caller_identity()
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 694, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 714, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/signers.py", line 93, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.9/site-packages/botocore/signers.py", line 165, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.9/site-packages/botocore/auth.py", line 378, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

When I run 

    okta-awscli --debug --verbose --profile=my_iam

everything is fine.

**Environment (please complete the following information):**
 - OS: MacOS
 - Version of okta-awscli you're running. 0.5.0

**Comment by danw-mpl** [comment]
We have the same issue - slight difference is that we're supplying `--okta-profile` to deal with different AWS accounts.

For us, the workaround is to supply both the `--okta-profile` and `--profile` flags.

OS: WSL2 (Ubuntu 20.04)
Version: 0.5.0
Python: 3.6.9

**Comment by tdmalone** [comment]
I also got this error, when using both `--okta-profile` and `--profile`.

I had the profile already created in `~/.aws/credentials`, but with just a `region` set. This seemed to be causing `okta-awscli` to assume that all the necessary fields existed, and it errored with `NoCredentialsError: Unable to locate credentials`.

Removing the profile completely fixed the issue, as okta-aws-cli then recreated it from scratch.
(I presume adding dud values for `aws_access_key_id`, `aws_secret_access_key`, and `aws_session_token` may have also resolved it).
